Improve token-specified login flow.
PennyLaneAI/pennylane-qiskit pull request #169
Opened 2021-12-13 20:30 UTC by TannerRogalsky

Creating multiple `IBMQDevice`s with credentials initialized from an environment variable tried to `enable_account` while an account already active. This PR fixes that while still allowing new environment tokens to specify new accounts to authenticate against.

2021-12-14 16:19 UTC, antalszava requested changes
Hi @TannerRogalsky, thank you so much for this change! :slightly_smiling_face: :tada: 

It might be worth adding one more test case just to make sure that all cases are covered.

It looks that the IBMQ token used in the device test suite is not exposed when making a PR from a forked PR. We have a mechanism in place to skip tests in such cases, it required a small addition.

As a result, CodeCov will likely not pass because the related tests are being skipped (I'll create an issue related to this).

2021-12-14 16:46 UTC, antalszava commented
We could add `# pragma: no cover` to the lines that are not reported to CodeCov and remove those once we've resolved #173.

2021-12-15 18:57 UTC, TannerRogalsky commented
@antalszava I think I've got everything that you requested. Let me know if it's not how you envisioned.

2021-12-15 19:36 UTC, antalszava approved these changes
Looks good to me! :tada: Thank you for this addition @TannerRogalsky :slightly_smiling_face:

2021-12-15 19:36 UTC, antalszava commented on tests/test_ibmq.py
> +def test_load_from_env_multiple_device(token, monkeypatch):
```suggestion
def test_load_from_env_multiple_device(token, monkeypatch):
    """Test creating multiple IBMQ devices when the environment variable
    for the IBMQ token was set.""""
```

2021-12-15 19:36 UTC, antalszava commented on tests/test_ibmq.py
> +def test_load_from_env_multiple_device_and_token(monkeypatch):
```suggestion
def test_load_from_env_multiple_device_and_token(monkeypatch):
    """Test creating multiple devices when the different tokens are defined
    using an environment variable.""""
```

2021-12-15 19:38 UTC, TannerRogalsky commented
Thank YOU for suggestions and guidance!

2021-12-15 22:34 UTC, merged